services:
    app:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        container_name: blog-mahad
        volumes:
            - ./.env.production:/var/www/html/.env
            - ./storage:/var/www/html/storage
            - ./bootstrap/cache:/var/www/html/bootstrap/cache
        restart: unless-stopped
        env_file:
            - .env.production
        networks:
            - private-net
    scheduler:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        container_name: blog-mahad-scheduler
        command: php artisan schedule:work
        volumes:
            - ./.env.production:/var/www/html/.env
        depends_on:
            - app

    nginx:
        image: nginx:1.27-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - '8100:80'
        volumes:
            - ./docker/production/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./storage:/var/www/html/storage:ro
        depends_on:
            - app
        networks:
            - private-net

networks:
    private-net:
        external: true
