services:
    app:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        container_name: blog-mahad
        volumes:
            - ./storage:/var/www/html/storage
        restart: unless-stopped
        env_file:
            - .env.production
        networks:
            - private-net
    scheduler:
        build:
            context: .
            dockerfile: docker/production/Dockerfile
        container_name: blog-mahad-scheduler
        command: php artisan schedule:work
        volumes:
            - .:/var/www/html
        depends_on:
            - app

    nginx:
        image: nginx:1.27-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - '8100:80' # debug akses langsung kalau perlu
        volumes:
            - ./storage:/var/www/html/storage
            - ./docker/production/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        networks:
            - private-net

networks:
    private-net:
        external: true
